# Site settings
title: Wajahat Ali
email: termazie@gmail.com
url: https://github.com/wajahat16079
description: "Welcome to my portfolio website. I am a Data Scientist with expertise in Statistical Analysis, Data Visualization, Machine Learning, and Web Development. Explore my work, projects, and experience."
keywords: "Data Science, Machine Learning, Statistical Analysis, Data Visualization, R, Python, Web Development, R Shiny, R Studio, Dashboarding"
skills: "Data Scientist - Statistical Analyst - Machine Learning Engineer - R Shiny Web Developer"
meta_author: Ali Wajahat

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
contact: static

# Contact form:
testimonials: static

# If you use disqus you need disqus shortname
disqus_shortname: wajahat-portfolio

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c # A custom shade of green representing growth and progress
  primary-rgb: "24,188,156" # Matching RGB values
  secondary: 2c3e50 # A deep blue for a professional and trustworthy feel
  secondary-dark: 233140 # Darker variant of the secondary color

# Footer settings
footer:
  copyright: Wajahat Ali
  location: Waterloo, Canada
  social: Connect with me
  credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

social:
  - title: youtube
    url: https://www.youtube.com/@Viz_IT
  - title: github
    url: http://github.com/wajahat16079
  - title: linkedin
    url: https://www.linkedin.com/in/swajahatali/

# Postal address
address:
  - line: Waterloo, Ontario
  - line: Canada


# Build settings
markdown: kramdown
permalink: pretty

# For posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/:categories/:title/"
